stages:
  - validate
  - plan
  - apply
  - destroy
image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
before_script:
  - export AWS_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - rm -rf .terraform
  - terraform --version
  - terraform init -backend-config "key=terraform/us-east-1/dev/tranning.tfstate" -backend-config "bucket=179623033511-terraform-states" -backend-config "dynamodb_table=179623033511_terraform_statelock" -backend-config "region=us-east-1"

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan

apply:
  stage: apply
  script:
    - terraform apply --auto-approve
  
destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve
  when: manual